### ISSUE TITLE
Support for code mirror 5.9

### ISSUE THREAD

**Issue by shaunbowe** [aullman/opentok-editor#1]
When using this code with the latest version of code mirror the clike languages do not work. Once you get past a single line these errors occurs constantly.

The base length of the second operation has to be the target length of the first operation
Cannot compose operations: first operation is too long.

**Comment by shaunbowe** [comment]
Add PR #2 to fix this issue.

**Comment by aullman** [comment]
Fixed with #3

**Comment by satyanarayanaAmzur** [comment]
hi aullman ,i'm working with opentok-editor plugin,for my coding application which was shared among the more then one user at a time ,when two or more users typing at the same line it was stop sync the changes between the two ends
