### ISSUE TITLE
If two participants delete at the same time it breaks the editor

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-editor#4]
Yeah, I managed to reproduce the problem by deleting from 2 editors at the same time:
1. Open up the editor on 2 separate machines
2. Click into the editor at the same point on both machines
3. Repeatedly press the delete button on both machines simultaneously

Result: You get an error in the console about "base length not equal" and now updates in the editor are no longer shared between the two machines.

**Comment by aullman** [comment]
It looks like this is the same issue: https://github.com/Operational-Transformation/ot.js/issues/30

**Comment by aullman** [comment]
This is fixed in v0.3.2 with https://github.com/aullman/opentok-editor/commit/efad474ea90ad9751515ef4206490df537c5bc17

**Comment by jackycute** [comment]
Thank you @aullman 
This is what I actually needed.

**Comment by satyanarayanaAmzur** [comment]
hi aullman,i have a issue like above but the situation is like below
"**out of sync when typing on same cursor position on several clients**" it was giving error like below
1."**The operation's base length must be equal to the string's length**"
and 2."**Both operations have to have the same base length**"
3."**The base length of the second operation has to be the target length of the first operation**" then it terminated the sync between the docs ,and i know these are from the library but i want to show  an alert about what went wrong but still the code sync was not coming to normal stage and being unresponsive until i refresh the page .

please help me on this, regarding making code editor responding back with previously valid code (means roll back) ,please suggest me any possible ways 

thank you very much in advance

**Comment by satyanarayanaAmzur** [comment]
hi aullaman ,i'm eagerly waiting for your response,please help on this issue
